#!/bin/bash
# Deploys the built host and registers it with every browser present.
# Invoked by `make install` — run that rather than this.
#
# The Windows kit does this with .bat files and registry writes; the macOS
# equivalent is a JSON manifest dropped into each browser's
# NativeMessagingHosts directory. Nothing is installed system-wide, no launch
# agent is created, and no sudo is required.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${HOME}/Library/Application Support/eProcSigner"
HOST_NAME="com.dxc.eproc.pki"
CHROME_EXT="oneboplbahpaldoloieajnbibaeocdlj"
FIREFOX_EXT="3d0c2a9fddbf0b1366f05c90a62ddf6ab8ca3163@eprocgok"

say() { printf '  %-8s %s\n' "$1" "$2"; }

JAVA_BIN="${ESIGNER_JAVA:-$(command -v java || true)}"
[ -x "$JAVA_BIN" ] || { echo "ERROR: no java. Run via 'make install'." >&2; exit 1; }
[ -f "${ROOT}/dist/esigner-mac.jar" ] || { echo "ERROR: not built. Run 'make build'." >&2; exit 1; }

# ---------------------------------------------------------------- files ------
mkdir -p "$DEST"
cp "${ROOT}/dist/esigner-mac.jar" "$DEST/"
cp "${ROOT}/lib/eSigner.jar"      "$DEST/"
cp "${ROOT}/run-host.sh"          "$DEST/"
chmod +x "$DEST/run-host.sh"

# The vendor PKCS#11 module links only against macOS' own PCSC.framework, so it
# runs fine from here — no root, no .pkg install, and uninstall takes it away
# again. A system-wide vendor install, if present, still wins below.
if ls "${ROOT}"/lib/libcastle*.dylib >/dev/null 2>&1; then
    cp "${ROOT}"/lib/libcastle*.dylib "$DEST/"
fi
say files "$DEST"

# ---------------------------------------------------------------- pkcs11 -----
LIB=""
for c in /usr/local/lib/libcastle_v2.1.0.0.dylib \
         /usr/local/lib/libcastle*.dylib \
         "$DEST"/libcastle*.dylib \
         /Library/Frameworks/eps2003csp11.framework/Versions/A/eps2003csp11 \
         /usr/local/lib/libeps2003csp11.dylib; do
    [ -r "$c" ] && LIB="$c" && break
done

ARCH_LINE=""
if [ -n "$LIB" ]; then
    say pkcs11 "$LIB"
    if command -v lipo >/dev/null && ! lipo -archs "$LIB" 2>/dev/null | grep -q arm64; then
        if [ "$(uname -m)" = "arm64" ]; then
            ARCH_LINE="arch=x86_64"
            say "" "(x86_64-only -> host will run under Rosetta)"
        fi
    fi
else
    say pkcs11 "NOT FOUND - run 'make deps', then this again"
fi

CONF="${DEST}/esigner.properties"
{
    echo "# eProcurement eSigner (macOS). Regenerated by make install."
    echo "java.bin=${JAVA_BIN}"
    [ -n "$ARCH_LINE" ] && echo "$ARCH_LINE"
    if [ -n "$LIB" ]; then
        echo "pkcs11.library=${LIB}"
    else
        echo "# pkcs11.library=/usr/local/lib/libcastle_v2.1.0.0.dylib"
    fi
    echo "# pkcs11.slotListIndex=0"
} > "$CONF"
say config "$CONF"

# ---------------------------------------------------------------- manifests --
# Written once and read by the browser at every startup, so the registration
# survives reboots with nothing running in between.
install_chromium_manifest() {
    dir="$1"; label="$2"
    [ -d "$(dirname "$dir")" ] || return 0
    mkdir -p "$dir"
    cat > "${dir}/${HOST_NAME}.json" <<JSON
{
  "name": "${HOST_NAME}",
  "description": "eProcurement digital signing host (macOS)",
  "path": "${DEST}/run-host.sh",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://${CHROME_EXT}/"
  ]
}
JSON
    say host "$label"
}

SUPPORT="${HOME}/Library/Application Support"
install_chromium_manifest "${SUPPORT}/Google/Chrome/NativeMessagingHosts"        "Chrome"
install_chromium_manifest "${SUPPORT}/Google/Chrome Beta/NativeMessagingHosts"   "Chrome Beta"
install_chromium_manifest "${SUPPORT}/Google/Chrome Canary/NativeMessagingHosts" "Chrome Canary"
install_chromium_manifest "${SUPPORT}/Chromium/NativeMessagingHosts"             "Chromium"
install_chromium_manifest "${SUPPORT}/Microsoft Edge/NativeMessagingHosts"       "Edge"
install_chromium_manifest "${SUPPORT}/BraveSoftware/Brave-Browser/NativeMessagingHosts" "Brave"

if [ -d "${SUPPORT}/Mozilla" ] || [ -d "/Applications/Firefox.app" ]; then
    mkdir -p "${SUPPORT}/Mozilla/NativeMessagingHosts"
    cat > "${SUPPORT}/Mozilla/NativeMessagingHosts/${HOST_NAME}.json" <<JSON
{
  "name": "${HOST_NAME}",
  "description": "eProcurement digital signing host (macOS)",
  "path": "${DEST}/run-host.sh",
  "type": "stdio",
  "allowed_extensions": ["${FIREFOX_EXT}"]
}
JSON
    say host "Firefox"
fi

echo
echo "Installed. Quit the browser completely (Cmd-Q) and reopen it."
[ -z "$LIB" ] && echo "NOTE: no PKCS#11 module yet - signing will fail until 'make deps' runs."
exit 0
